### ISSUE TITLE
PageID format changes

### ISSUE THREAD

**Issue by N7WEra** [igor-kupczynski/notion-exporter#3]
Hi, 

Notion changed the format of the Page ID, it's no longer a random long value, but rather a page name and a random value.

The current workflow fails as it can't import it based on the page ID format.

022/02/11 11:03:11 can't export page: '********-c5454f30bbf24e7bbc061535e8666935' is not a valid notion id
Complete job

Any idea how to fix it?

Thanks in advance.

**Comment by igor-kupczynski** [comment]
Sorry, I no longer use notion. Will put a banner in the README.
